#!/bin/bash

string=$(acpi -b)
arr=($string)

stat=${arr[2]::-1}
label="Battery"

if [ "$stat" = 'Full' ]; then
    icon=""
    color="#FFFFFF"
    time="Full"
    percent=${arr[3]::-1}
else
    percent=${arr[3]::-2}
    time=${arr[4]::-3}
    if [ "$stat" = 'Charging' ]; then
        label="Charging"
        icon=""
        color="#FFFFFF"
    else
        if [[ $percent -lt 10 ]]; then
            icon=""
            color="#FF0000"
        elif [[ $percent -lt 15 ]]; then
            icon=""
            color="#FF7700"
        elif [[ $percent -lt 25 ]]; then
            icon=""
            color="#FFDD00"
        elif [[ $percent -lt 35 ]]; then
            icon=""
            color="#FFFF77"
        elif [[ $percent -lt 90 ]]; then
            icon=""
            color="#FFFFEE"
        else
            icon=""
            color="#FFFFFF"
        fi
    fi
fi

# echo "$icon  $percent%,  $time"
echo "$label: $percent%, $time"
echo ""
echo $color
