#!/bin/bash

temp=$(sh -c '/usr/share/i3blocks/temperature')

usage=$(grep 'cpu ' /proc/stat | awk '{printf "%.2f%%", ($2+$4)*100/($2+$4+$5)}')
memory=$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')

echo "CPU:  $usage,  $temp   MEM:  $memory"
