#!/bin/bash

temp=$(sh -c '/usr/share/i3blocks/temperature')

usage=$(top -bn 2 -d 0.01 | grep '^%Cpu' | tail -n 1 | gawk '{print $2+$4+$6}')
memory=$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')

echo "CPU: $usage, $temp MEM: $memory"
