#!/bin/bash

string=$(amixer get Master)
volume=$(expr "$string" : '.*\[\(.*\)%\].*')

if [[ $string == *"[on]" ]]; then
    if [[ $volume -lt 20 ]]; then
        echo "Vol: $volume%"
    elif [[ $volume -lt 50 ]]; then
        echo "Vol: $volume%"
    else
        echo "Vol: $volume%"
    fi
        
else
    echo "Vol: Mute"
    # echo ""
    echo "Mute"
    echo "#777777"
fi
